### ISSUE TITLE
Failing check when submitting parameters to CRAN

### ISSUE THREAD

**Issue by strengejacke** [IndrajeetPatil/broomExtra#23]
I was asked to send an update of _parameters_ to CRAN, however, the check for the current CRAN version of _broomExtra_ fails:

```
New result: ERROR
    Running ‘spelling.R’ [0s/0s]
    Running ‘testthat.R’ [10s/10s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > library(testthat)
    > library(broomExtra)
    > 
    > test_check("broomExtra")
    ── 1. Failure: hybrid methods works (@test-hybrid_generics.R#57)  ──────────────
    dim(tidy_parameters(mod_mixor)) not equal to c(8L, 8L).
    1/2 mismatches
    [2] 9 - 8 == 1
    
    ══ testthat results  ═══════════════════════════════════════════════════════════
    [ OK: 28 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
    1. Failure: hybrid methods works (@test-hybrid_generics.R#57) 
    
    Error: testthat unit tests failed
    Execution halted
```

I see that you have fixed this issue already, so my question is: are you able to submit an update of broomExtra to CRAN, where this test already works? I think the test for broomExtra needs to be fixed and submitted to CRAN first, before I can update parameters.

**Comment by IndrajeetPatil** [comment]
Thanks. Submitted the fixed version to `CRAN`.

Usually, you wouldn't have to wait for me to submit the new version. You can also just mention in the `cran_comments` that you have informed the developer and that they have agreed to update the package for the breaking packages and the maintainers will accept your submission.

**Comment by IndrajeetPatil** [comment]
It's on CRAN now!
