### ISSUE TITLE
Request for adding space after formula terms for factor variables

### ISSUE THREAD

**Issue by IsadoraBM** [IndrajeetPatil/broomExtra#29]
I'd like to add a space to the factor variables so that when the tidy_parameters table is produced there is separation between the variable name and the factor levels. E.g. EducationLow becomes Education Low. Ideally, it would be even better if only the first level kept the variable name and all other subsequent ones dropped it. This would then make piping into dwplot() produce a graph that has, for example:
Age
Education Low 
Medium
High
Gender Male
Even more ideal, if there could be a way of appending \n (ref ___) with the reference category for the first level so that the dwplot would produce:
Age
Education Low
(ref Undisclosed)
Medium
High
Gender Male
(ref Female)

**Comment by IndrajeetPatil** [comment]
Hi,

This is all produced under the hood by `{parameters}` package.

You can create an issue with a reproducible example as a feature request here:
https://github.com/easystats/parameters/issues
