### ISSUE TITLE
CRAN archival

### ISSUE THREAD

**Issue by fkohrt** [IndrajeetPatil/broomExtra#35]
As of 2022-10-09, [broomExtra's CRAN page](https://cran.r-project.org/package=broomExtra) says

> Archived on 2022-07-07 at the maintainer's request.

Does this mean that {broomExtra} is not maintained anymore or was there a different reason for this request? I love {broomExtra} and its summary interface!

**Comment by IndrajeetPatil** [comment]
Yes, {broomExtra} is not maintained anymore because there are better solutions out there that should be preferred over it.

Have a look at: https://easystats.github.io/parameters/

**Comment by fkohrt** [comment]
I see. So `broomExtra::tidy()` is roughly equivalent to `parameters::parameters()` and `performance::performance()` may be closest to `broomExtra::glance()` - or did I miss something? Haven't used easystats a lot so far.

**Comment by IndrajeetPatil** [comment]
Exactly!

For more, see: https://easystats.github.io/easystats/

**Comment by fkohrt** [comment]
Alright! Maybe set the lifecycle stage in your README to "deprecated" so people can see it upfront :)

**Comment by IndrajeetPatil** [comment]
Done! 

Hadn't touched the repo in a long time, so forgot to update for the archival.
